version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
  database:
    image: mongo:4.4
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./src/config/database:/data/db
volumes:
  dependencies:
