version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
  database:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./src/config/database:/data/db
volumes:
  dependencies:
